#!/bin/bash

#  _     _          
# | |   | |           Henrique Borges (henriquehbr)
# | |__ | |__  _ __   https://github.com/henriquehbr
# | '_ \| '_ \| '__|  https://henriquehbr.dev
# | | | | |_) | |     https://reddit.com/u/henriquehbr
# |_| |_|_.__/|_|

# Insert "mirrors" after "bootloader"
MODULES=(
  "variables"
  "validate-config"
  "partitioning"
  "formatting"
  "mirrors"
  "install-packages"
  "generate-fs-table"
  "timezone"
  "locales"
  "hostname"
  "users"
  "bootloader"
  "extra"
  "post-install"
)

MODULES=$(IFS=, ; echo "${MODULES[*]}")

curl -Ls https://raw.githubusercontent.com/henriquehbr/arsh/main/config > config
curl -Ls "https://raw.githubusercontent.com/henriquehbr/arsh/main/{$MODULES}" >> arsh

chmod +x arsh

source config
source arsh
