#!/bin/bash

# Exit in case of any errors on subshells
set -e

#  _     _
# | |   | |           Henrique Borges (henriquehbr)
# | |__ | |__  _ __   https://github.com/henriquehbr
# | '_ \| '_ \| '__|  https://henriquehbr.dev
# | | | | |_) | |     https://reddit.com/u/henriquehbr
# |_| |_|_.__/|_|

# Ignores both errors and output of `lscpu`
if lscpu | grep GenuineIntel > /dev/null 2>&1; then
  CPU='intel'
else
  CPU='amd'
fi

# Required in order to ensure system stability
CPU_PACKAGE="${CPU}-ucode"

BOOTLOADER_PACKAGES=(grub dosfstools os-prober mtools efibootmgr)
ESSENTIAL_PACKAGES=(base linux linux-firmware $CPU_PACKAGE)
INTERNET_PACKAGES=(networkmanager wpa_supplicant)
DEVELOPMENT_PACKAGES=(git vim unzip stow)
DEVELOPMENT_GROUP_PACKAGES=(base-devel)

EXTRA_OFFICIAL_PACKAGES=(xf86-video-fbdev xorg-xinit neovim dmenu dialog pulseaudio alsa-utils virtualbox inotify-tools linux-headers reflector xdg-user-dirs)
EXTRA_GROUP_PACKAGES=(xorg)
EXTRA_AUR_PACKAGES=(bspwm sxhkd lemonbar-xft-git xdo xtitle brave-bin)

ARSH_BOOT_PARTITION=/dev/sda1
ARSH_SWAP_PARTITION=/dev/sda2
ARSH_ROOT_PARTITION=/dev/sda3
